spring:
  config:
    activate:
      on-profile: prod
  jackson:
    time-zone: America/Bogota

server:
  port: ${SERVER_PORT:8086}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

resilience4j:
  circuitbreaker:
    instances:
      personal-service:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.malvinas: INFO
