-- Malvinas vehiculos-service — schema vehicles
CREATE SCHEMA IF NOT EXISTS vehicles;

CREATE TABLE IF NOT EXISTS vehicles.vehicle_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)    NOT NULL UNIQUE,
    capacity_kg DECIMAL(10,2),
    description VARCHAR(200),
    is_active   BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP      NOT NULL,
    modified_at TIMESTAMP      NOT NULL,
    created_by  VARCHAR(255),
    modified_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS vehicles.vehicles (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_plate             VARCHAR(10)  NOT NULL UNIQUE,
    vehicle_type_id           BIGINT       NOT NULL REFERENCES vehicles.vehicle_types(id),
    brand                     VARCHAR(255),
    model                     VARCHAR(255),
    year                      SMALLINT,
    color                     VARCHAR(255),
    mileage                   INTEGER      NOT NULL DEFAULT 0,
    soat_expiry_date          DATE,
    technical_inspection_date DATE,
    status                    VARCHAR(2)   NOT NULL DEFAULT '01',
    is_active                 BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at                TIMESTAMP    NOT NULL,
    modified_at               TIMESTAMP    NOT NULL,
    created_by                VARCHAR(255),
    modified_by               VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS vehicles.status_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id      BIGINT     NOT NULL REFERENCES vehicles.vehicles(id),
    previous_status VARCHAR(2) NOT NULL,
    new_status      VARCHAR(2) NOT NULL,
    reason          VARCHAR(200),
    employee_id     BIGINT,
    created_at      TIMESTAMP  NOT NULL,
    modified_at     TIMESTAMP  NOT NULL,
    created_by      VARCHAR(255),
    modified_by     VARCHAR(255)
);
