-- Malvinas cargas-service — schema loads
CREATE SCHEMA IF NOT EXISTS loads;

CREATE TABLE IF NOT EXISTS loads.loads (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_plate      VARCHAR(10)  NOT NULL,
    mobilizer_id       BIGINT       NOT NULL,
    status             VARCHAR(2)   NOT NULL DEFAULT '01',
    loading_plant      VARCHAR(100),
    remarks            TEXT,
    loading_start_time TIMESTAMP,
    loading_end_time   TIMESTAMP,
    created_at         TIMESTAMP    NOT NULL,
    modified_at        TIMESTAMP    NOT NULL,
    created_by         VARCHAR(255),
    modified_by        VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS loads.load_details (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_id     BIGINT       NOT NULL REFERENCES loads.loads(id),
    description VARCHAR(200) NOT NULL,
    quantity    INTEGER      NOT NULL DEFAULT 1,
    weight_kg   DECIMAL(10,2),
    remark      VARCHAR(200),
    created_at  TIMESTAMP    NOT NULL,
    modified_at TIMESTAMP    NOT NULL,
    created_by  VARCHAR(255),
    modified_by VARCHAR(255)
);
