-- Malvinas rutas-service — schema routes
CREATE SCHEMA IF NOT EXISTS routes;

CREATE TABLE IF NOT EXISTS routes.delivery_points (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    address     VARCHAR(200),
    district    VARCHAR(255),
    reference   VARCHAR(200),
    contact     VARCHAR(100),
    phone       VARCHAR(15),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL,
    modified_at TIMESTAMP    NOT NULL,
    created_by  VARCHAR(255),
    modified_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS routes.dispatches (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_plate          VARCHAR(10)  NOT NULL,
    driver_id              BIGINT       NOT NULL,
    helper1_id             BIGINT,
    helper2_id             BIGINT,
    load_id                BIGINT,
    priority               VARCHAR(2)   NOT NULL DEFAULT '02',
    status                 VARCHAR(2)   NOT NULL DEFAULT '01',
    loading_order_code     VARCHAR(20)  UNIQUE,
    scheduled_departure_time TIME,
    actual_departure_time  TIMESTAMP,
    return_time            TIMESTAMP,
    remarks                TEXT,
    created_at             TIMESTAMP    NOT NULL,
    modified_at            TIMESTAMP    NOT NULL,
    created_by             VARCHAR(255),
    modified_by            VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS routes.dispatch_points (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispatch_id       BIGINT    NOT NULL REFERENCES routes.dispatches(id),
    delivery_point_id BIGINT    NOT NULL REFERENCES routes.delivery_points(id),
    visit_order       SMALLINT  NOT NULL DEFAULT 1,
    delivery_status   VARCHAR(2),
    delivery_time     TIMESTAMP,
    remark            VARCHAR(200),
    created_at        TIMESTAMP NOT NULL,
    modified_at       TIMESTAMP NOT NULL,
    created_by        VARCHAR(255),
    modified_by       VARCHAR(255)
);
